version: "3"

services:
  mongodb:
    image: mongo
    env_file:
      - mongodb.docker.env
    networks:
      - mongodb
    volumes:
      - /var/mongodb:/data/db

  application:
    image: master-forms-api
    env_file:
      - application.docker.env
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge